version: 0.0
os: linux

file_exists_behavior: OVERWRITE

hooks:
  ApplicationStop:
    - location: scripts/server_stop.sh
      timeout: 300
      runas: root

   ApplicationStart:
    - location: scripts/server_start.sh
      timeout: 300
      runas: root
