version: 0.0
os: linux

files:
  - source: target/HelloWorld-0.0.1-SNAPSHOT.war
    destination: /opt/tomcat/webapps/
    overwrite: true

hooks:
  BeforeInstall:
    - location: scripts/install_tomcat.sh
      timeout: 300
      runas: root

  AfterInstall:
    - location: scripts/deploy_war.sh
      timeout: 120
      runas: tomcat

  ApplicationStart:
    - location: scripts/restart_tomcat.sh
      timeout: 60
      runas: root
