version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11  # or your required version
    commands:
      - echo Installing Maven...
      - curl -sL https://apache.osuosl.org/maven/maven-3/3.8.8/binaries/apache-maven-3.8.8-bin.tar.gz | tar xz -C /tmp
      - export MAVEN_HOME=/tmp/apache-maven-3.8.8
      - export PATH=$MAVEN_HOME/bin:$PATH
      - mvn --version

  pre_build:
    commands:
      - echo Running tests...
      - mvn test

  build:
    commands:
      - echo Building WAR file...
      - mvn clean package -DskipTests=false

  post_build:
    commands:
      - echo Build completed at `date`

artifacts:
  files:
    - target/*.war

cache:
  paths:
    - '/root/.m2/**/*'
