version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - echo "Installing dependencies..."
      - mvn -version

  pre_build:
    commands:
      - echo "Cleaning the project..."
      - mvn clean

  build:
    commands:
      - echo "Building the project..."
      - mvn package

  post_build:
    commands:
      - echo "Build completed successfully!"
      - ls target/

artifacts:
  files:
    - target/*.jar
