version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - echo "Install phase: using preinstalled Maven"
      - mvn -version

  pre_build:
    commands:
      - echo "Pre-build phase: cleaning project"
      - mvn clean

  build:
    commands:
      - echo "Build phase: packaging project"
      - mvn package

  post_build:
    commands:
      - echo "Post-build phase: completed successfully"
      - echo "Build artifact: target/*.jar"

artifacts:
  files:
    - target/*.jar
